language: php

php:
    - 7.0
    - nightly

script:
    - phpize
    - ./configure
    - make
    - REPORT_EXIT_STATUS=1 TEST_PHP_EXECUTABLE=`which php` php -n run-tests.php -n -d extension_dir=./modules/ -d extension=shmt.so -q --show-diff

