language: php

php:
    - 7.0
    - nightly

script:
    - phpize
    - ./configure
    - make
    - TEST_PHP_EXECUTABLE=`which php` php -n run-tests.php -n -d extension_dir=./modules/ -d extension=shmt.so -q -x --show-diff

